backend = "glx";
vsync = true;

corner-radius = 14;
round-borders = 1;

shadow = true;
shadow-radius = 20;
shadow-opacity = 0.35;
shadow-offset-x = -10;
shadow-offset-y = -10;

fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;

blur:
{
  method = "dual_kawase";
  strength = 2;
};

blur-background = true;
blur-background-fixed = true;

inactive-opacity = 0.92;
active-opacity = 1.0;

opacity-rule = [
  "92:class_g = 'kitty'",
  "85:class_g = 'floating_lyrics'",
  "0:class_g = 'GLava'"
];

rounded-corners-exclude = [
  "class_g = 'GLava'"
];

shadow-exclude = [
  "class_g = 'GLava'"
];
