# --- The Glass ---
background_opacity 0.8
dynamic_background_opacity yes

# --- TokyoNight / Neovim Blue ---

background #1f2335
#foreground #7dcfff
cursor     #ffffff

# Black / Gray
color0     #15161e
color8     #414868

# Red
color1     #f7768e
color9     #ff7a93

# Green
color2     #73daca
color10    #b4f9f8

# Yellow
color3     #e0af68
color11    #ff9e64

# Blue
color4     #7aa2f7
color12    #7dcfff

# Magenta
color5     #bb9af7
color13    #c0a7f9

# Cyan
color6     #7dcfff
color14    #a2d2fb

# White
color7     #ffffff
color15    #ffffff
