[bar/main]
width = 100%
height = 24pt
radius = 12

; rgba(20, 20, 20, 0.85) Background
background = #D9141414
; Parchment white fallback
foreground = #ebdbb2

; rgba(51, 204, 255, 0.4) border
border-size = 2pt
border-color = #6633ccff

padding-left = 1
padding-right = 1
module-margin = 1

; Fonts (JetBrains Mono weight 900 & emoji fallback)
font-0 = "JetBrainsMono Nerd Font:style=Heavy:size=11;3"
font-1 = "Noto Color Emoji:scale=10;3"

modules-left = xworkspaces
modules-center = date
modules-right = pulseaudio network battery systray

[module/xworkspaces]
type = internal/xworkspaces
; Roman numeral mapping
icon-0 = 1;I
icon-1 = 2;II
icon-2 = 3;III
icon-3 = 4;IV
icon-4 = 5;V
icon-5 = 6;VI
icon-6 = 7;VIC
icon-7 = 8;VICK
icon-8 = 9;VICKY
icon-default = 

; Active workspace (cyan text, faint cyan bg)
label-active = %icon%
label-active-foreground = #33ccff
label-active-background = #3333ccff
label-active-padding = 2

; Occupied/Empty workspaces (grey)
label-occupied = %icon%
label-occupied-foreground = #595959
label-occupied-padding = 2
label-empty = %icon%
label-empty-foreground = #595959
label-empty-padding = 2

[module/date]
type = internal/date
interval = 1
; "⏳ {:%H:%M}" format
date = "⏳ %H:%M"
label = %date%
; Parchment white
label-foreground = #ebdbb2
; rgba(40, 40, 40, 0.8) Dark wood background
label-background = #CC282828
label-padding = 2

[module/battery]
type = internal/battery
full-at = 100
low-at = 15
; "🕯️ {capacity}%" format
format-charging = "🕯️ <label-charging>"
format-discharging = "🕯️ <label-discharging>"
label-charging = %percentage%%
label-discharging = %percentage%%
; Moss green
format-charging-foreground = #b8bb26
format-discharging-foreground = #b8bb26
format-charging-background = #CC282828
format-discharging-background = #CC282828
format-charging-padding = 2
format-discharging-padding = 2

[module/network]
type = internal/network
interface-type = wireless
; "📜 {essid}" format
format-connected = "📜 <label-connected>"
label-connected = %essid%
; Faded steel blue
formar-connected-foreground = #83a598
format-connected-background = #CC282828
format-connected-padding = 2

; "🐎 No Courier" format
format-disconnected = "🐎 No Courier"
format-disconnected-foreground = #83a598
format-disconnected-background = #CC282828
format-disconnected-padding = 2

[module/pulseaudio]
type = internal/pulseaudio
; "📯 {volume}%" format
format-volume = "📯 <label-volume>"
label-volume = %percentage%%
; Faded royal purple
format-volume-foreground = #d3869b
format-volume-background = #CC282828
format-volume-padding = 2

; "🔇 Silenced" format
label-muted = "🔇 Silenced"
format-muted-foreground = #d3869b
format-muted-background = #CC282828
format-muted-padding = 2

[module/systray]
type = internal/tray
tray-position = none
tray-spacing = 8pt
; Match your dark background
tray-background = #D9141414
